# Generated by Django 4.2.4 on 2023-08-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_designation_alter_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_onboarding',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
