# Generated by Django 4.2.4 on 2023-08-24 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_name_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
